# Banco — vem de variáveis de ambiente
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# Flyway em Produção - Apenas valida se o banco está atualizado
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logs
logging.level.com.cafeteria=INFO
logging.level.org.springframework.kafka=WARN

# Segurança
server.error.include-stacktrace=never
server.error.include-message=never
# Prod
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=code-and-coffee-api-prod
